FrontEnd/Controllers/AdminRutasController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Controllers
{
    public class AdminRutasController : Controller
    {
        private readonly ILogger<AdminRutasController> _logger;

        public AdminRutasController(ILogger<AdminRutasController> logger)
        {
            _logger = logger;
        }

        //[Authorize(Roles = "supervisor")]
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/Controllers/UnidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BackEnd.Datos;
using BackEnd.Entidades;
using BackEnd.Negocio;

namespace FrontEnd.Controllers
{
    public class UnidadesController : Controller
    {
        private readonly RutasContext _context;
        private readonly IActividades actividades;

        public UnidadesController()
        {
            _context = new RutasContext();
            actividades = new Actividades();
        }

        // GET: Unidades
        public async Task<IActionResult> Index()
        {
            var rutasContext = _context.Unidades.Include(u => u.IdEstadoDeUnidadNavigation);
            return View(await rutasContext.ToListAsync());
        }

        // GET: Unidades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Consultar",
                    Tipo = new Unidades().GetType().Name,
                    Objeto = new Unidades  ().ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            var unidades = await _context.Unidades
                .Include(u => u.IdEstadoDeUnidadNavigation)
                .FirstOrDefaultAsync(m => m.IdUnidad == id);
            if (unidades == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Consultar",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            actividades.Agregar(new Actividad()
            {
                Accion = "Consultar",
                Tipo = unidades.GetType().Name,
                Objeto = unidades.ToString(),
                Usuario = HttpContext.User.Identity.Name,
                Completada = true,
                FechaHora = DateTime.Now
            });

            return View(unidades);
        }

        // GET: Unidades/Create
        public IActionResult Create()
        {
            ViewData["IdEstadoDeUnidad"] = new SelectList(_context.EstadosDeUnidad, "IdEstadoDeUnidad", "Descripcion");
            return View();
        }

        // POST: Unidades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUnidad,NumeroDePlaca,CapacidadDePasajeros,IdEstadoDeUnidad")] Unidades unidades)
        {
            if (ModelState.IsValid)
            {
                _context.Add(unidades);
                await _context.SaveChangesAsync();

                actividades.Agregar(new Actividad()
                {
                    Accion = "Crear",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = true,
                    FechaHora = DateTime.Now
                });

                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstadoDeUnidad"] = new SelectList(_context.EstadosDeUnidad, "IdEstadoDeUnidad", "Descripcion", unidades.IdEstadoDeUnidad);

            actividades.Agregar(new Actividad()
            {
                Accion = "Crear",
                Tipo = unidades.GetType().Name,
                Objeto = unidades.ToString(),
                Usuario = HttpContext.User.Identity.Name,
                Completada = false,
                FechaHora = DateTime.Now
            });

            return View(unidades);
        }

        // GET: Unidades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Modificar",
                    Tipo = new Unidades().GetType().Name,
                    Objeto = new Unidades().ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            var unidades = await _context.Unidades.FindAsync(id);
            if (unidades == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Modificar",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }
            ViewData["IdEstadoDeUnidad"] = new SelectList(_context.EstadosDeUnidad, "IdEstadoDeUnidad", "Descripcion", unidades.IdEstadoDeUnidad);
            return View(unidades);
        }

        // POST: Unidades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUnidad,NumeroDePlaca,CapacidadDePasajeros,IdEstadoDeUnidad")] Unidades unidades)
        {
            if (id != unidades.IdUnidad)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Modificar",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(unidades);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnidadesExists(unidades.IdUnidad))
                    {
                        actividades.Agregar(new Actividad()
                        {
                            Accion = "Modificar",
                            Tipo = unidades.GetType().Name,
                            Objeto = unidades.ToString(),
                            Usuario = HttpContext.User.Identity.Name,
                            Completada = false,
                            FechaHora = DateTime.Now
                        });

                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                actividades.Agregar(new Actividad()
                {
                    Accion = "Crear",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = true,
                    FechaHora = DateTime.Now
                });

                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstadoDeUnidad"] = new SelectList(_context.EstadosDeUnidad, "IdEstadoDeUnidad", "Descripcion", unidades.IdEstadoDeUnidad);

            actividades.Agregar(new Actividad()
            {
                Accion = "Modificar",
                Tipo = unidades.GetType().Name,
                Objeto = unidades.ToString(),
                Usuario = HttpContext.User.Identity.Name,
                Completada = false,
                FechaHora = DateTime.Now
            });

            return View(unidades);
        }

        // GET: Unidades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Eliminar",
                    Tipo = new Unidades().GetType().Name,
                    Objeto = new Unidades().ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            var unidades = await _context.Unidades
                .Include(u => u.IdEstadoDeUnidadNavigation)
                .FirstOrDefaultAsync(m => m.IdUnidad == id);
            if (unidades == null)
            {
                actividades.Agregar(new Actividad()
                {
                    Accion = "Eliminar",
                    Tipo = unidades.GetType().Name,
                    Objeto = unidades.ToString(),
                    Usuario = HttpContext.User.Identity.Name,
                    Completada = false,
                    FechaHora = DateTime.Now
                });

                return NotFound();
            }

            return View(unidades);
        }

        // POST: Unidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

FrontEnd/Views/AdminRutas/Index.cshtml
@{
    ViewData["Title"] = "Rutas";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <!-- Agrega enlaces a tus archivos CSS aquí si los tienes -->
    <link rel="stylesheet" href="./css/site.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        /* Estilos para el contenedor */
        .container {
            max-width: 1500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        /* Estilos para la tabla */
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }



        .table th, .table td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .table th {
            background-color: #f2f2f2;
        }

        .table tr:hover {
            background-color: #f0f0f0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <hr />
        <p class="text-body">Utilice estas opciones para administrar los accesos al portal.</p>

        <div class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-left box-shadow mb-3">
            <table class="table">
                <tr>
                    <th class="col-sm-3">Módulo</th>
                    <th class="col-sm-10">Descripción</th>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="Rutas" asp-action="Index">Rutas</a>
                    </td>
                    <td>
                        Establecer, ajustar o cancelar rutas.
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="EstadosDeUnidad" asp-action="Index">Estados de la unidad</a>
                    </td>
                    <td>
                        Establecer, ajustar o eliminar los estados posibles de una unidad.
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="Unidades" asp-action="Index">Unidades</a>
                    </td>
                    <td>
                        Incorporar, renovar o dar de baja unidades.
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="Conductores" asp-action="Index">Conductores</a>
                    </td>
                    <td>
                        Incluir, renovar o dar de baja conductores.
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="ConductoresPorUnidad" asp-action="Index">Asignar conductores a una unidad</a>
                    </td>
                    <td>
                        Asignar conductores a una unidad y desvincular los condutores asignados a una unidad.
                    </td>
                </tr>
                <tr>
                    <td>
                        <a class="btn-link" asp-controller="MontosPorRutaPorUnidad" asp-action="Index">Monto a recaudar</a>
                    </td>
                    <td>
                        Definir los importes a recolectar por fecha para cada unidad asignada a una ruta particular.
                    </td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>